spring:
  application:
    name: preStudy

  profiles:
    default: develop

  config:
    import:
      - database.yml

  datasource:
    driver-class-name: ${database.driver}
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}

logging:
  level:
    root: info
